import type { Skill } from "../schemas";

export const skills = [
  {
    id: "python",
    label: "Python",
    group: "programming",
    rolePriority: "data-engineer",
    evidenceRefs: [
      { kind: "project", id: "ai-sandbox" },
      { kind: "project", id: "centralgis" },
      { kind: "project", id: "jesa-eia-input-reduction" },
    ],
  },
  {
    id: "sql",
    label: "SQL",
    group: "programming",
    rolePriority: "data-engineer",
    evidenceRefs: [
      { kind: "project", id: "centralgis" },
      { kind: "project", id: "ocp-workforce-platform" },
      { kind: "project", id: "data-quality-kpi" },
    ],
  },
  {
    id: "apache-kafka",
    label: "Apache Kafka",
    group: "data-engineering",
    rolePriority: "data-engineer",
    evidenceRefs: [
      { kind: "project", id: "centralgis" },
      { kind: "project", id: "stock-market-etl" },
    ],
  },
  {
    id: "apache-spark",
    label: "Apache Spark",
    group: "data-engineering",
    rolePriority: "data-engineer",
    evidenceRefs: [
      { kind: "project", id: "stock-market-etl" },
      { kind: "project", id: "healthics" },
    ],
  },
  {
    id: "airflow",
    label: "Airflow",
    group: "data-engineering",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "stock-market-etl" }],
  },
  {
    id: "etl-elt",
    label: "ETL/ELT",
    group: "data-engineering",
    rolePriority: "data-engineer",
    evidenceRefs: [
      { kind: "project", id: "stock-market-etl" },
      { kind: "project", id: "data-quality-kpi" },
    ],
  },
  {
    id: "pandas",
    label: "Pandas",
    group: "data-engineering",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "jesa-eia-input-reduction" }],
  },
  {
    id: "fastapi",
    label: "FastAPI",
    group: "backend-and-web",
    rolePriority: "shared",
    evidenceRefs: [{ kind: "project", id: "ai-sandbox" }],
  },
  {
    id: "flask",
    label: "Flask",
    group: "backend-and-web",
    rolePriority: "shared",
    evidenceRefs: [{ kind: "project", id: "centralgis" }],
  },
  {
    id: "spring-boot",
    label: "Spring Boot",
    group: "backend-and-web",
    rolePriority: "software-engineer",
    evidenceRefs: [
      { kind: "project", id: "ocp-workforce-platform" },
      { kind: "project", id: "healthics" },
    ],
  },
  {
    id: "react",
    label: "React",
    group: "backend-and-web",
    rolePriority: "software-engineer",
    evidenceRefs: [{ kind: "project", id: "healthics" }],
  },
  {
    id: "angular",
    label: "Angular",
    group: "backend-and-web",
    rolePriority: "software-engineer",
    evidenceRefs: [{ kind: "project", id: "ocp-workforce-platform" }],
  },
  {
    id: "rest-apis",
    label: "REST APIs",
    group: "backend-and-web",
    rolePriority: "shared",
    evidenceRefs: [
      { kind: "project", id: "centralgis" },
      { kind: "project", id: "healthics" },
    ],
  },
  {
    id: "maplibre-gl-js",
    label: "MapLibre GL JS",
    group: "backend-and-web",
    rolePriority: "software-engineer",
    evidenceRefs: [{ kind: "project", id: "centralgis" }],
  },
  {
    id: "postgresql",
    label: "PostgreSQL",
    group: "data-stores",
    rolePriority: "shared",
    evidenceRefs: [
      { kind: "project", id: "ai-sandbox" },
      { kind: "project", id: "centralgis" },
      { kind: "project", id: "ocp-workforce-platform" },
      { kind: "project", id: "stock-market-etl" },
      { kind: "project", id: "data-quality-kpi" },
    ],
  },
  {
    id: "postgis",
    label: "PostGIS",
    group: "data-stores",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "centralgis" }],
  },
  {
    id: "mongodb",
    label: "MongoDB",
    group: "data-stores",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "stock-market-etl" }],
  },
  {
    id: "redis",
    label: "Redis",
    group: "data-stores",
    rolePriority: "shared",
    evidenceRefs: [{ kind: "project", id: "ai-sandbox" }],
  },
  {
    id: "minio",
    label: "MinIO",
    group: "data-stores",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "ai-sandbox" }],
  },
  {
    id: "hbase",
    label: "HBase",
    group: "data-stores",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "healthics" }],
  },
  {
    id: "power-bi",
    label: "Power BI",
    group: "analytics-and-bi",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "data-quality-kpi" }],
  },
  {
    id: "dax",
    label: "DAX",
    group: "analytics-and-bi",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "data-quality-kpi" }],
  },
  {
    id: "grafana",
    label: "Grafana",
    group: "analytics-and-bi",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "stock-market-etl" }],
  },
  {
    id: "scikit-learn",
    label: "scikit-learn",
    group: "ai-and-machine-learning",
    rolePriority: "data-engineer",
    evidenceRefs: [
      { kind: "project", id: "ai-sandbox" },
      { kind: "project", id: "jesa-eia-input-reduction" },
    ],
  },
  {
    id: "xgboost",
    label: "XGBoost",
    group: "ai-and-machine-learning",
    rolePriority: "data-engineer",
    evidenceRefs: [
      { kind: "project", id: "ai-sandbox" },
      { kind: "project", id: "jesa-eia-input-reduction" },
    ],
  },
  {
    id: "lightgbm",
    label: "LightGBM",
    group: "ai-and-machine-learning",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "ai-sandbox" }],
  },
  {
    id: "mlflow",
    label: "MLflow",
    group: "ai-and-machine-learning",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "ai-sandbox" }],
  },
  {
    id: "bert",
    label: "BERT",
    group: "ai-and-machine-learning",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "legal-text-classification" }],
  },
  {
    id: "hugging-face-transformers",
    label: "Hugging Face Transformers",
    group: "ai-and-machine-learning",
    rolePriority: "data-engineer",
    evidenceRefs: [{ kind: "project", id: "legal-text-classification" }],
  },
  {
    id: "azure",
    label: "Azure",
    group: "cloud-and-delivery",
    rolePriority: "shared",
    evidenceRefs: [{ kind: "project", id: "ai-sandbox" }],
  },
  {
    id: "docker",
    label: "Docker",
    group: "cloud-and-delivery",
    rolePriority: "shared",
    evidenceRefs: [
      { kind: "project", id: "ai-sandbox" },
      { kind: "project", id: "centralgis" },
      { kind: "project", id: "ocp-workforce-platform" },
      { kind: "project", id: "stock-market-etl" },
    ],
  },
  {
    id: "nginx",
    label: "Nginx",
    group: "cloud-and-delivery",
    rolePriority: "software-engineer",
    evidenceRefs: [{ kind: "project", id: "ai-sandbox" }],
  },
  {
    id: "ci-cd",
    label: "CI/CD",
    group: "cloud-and-delivery",
    rolePriority: "software-engineer",
    evidenceRefs: [{ kind: "project", id: "ocp-workforce-platform" }],
  },
  {
    id: "pytest",
    label: "Pytest",
    group: "testing",
    rolePriority: "shared",
    evidenceRefs: [{ kind: "project", id: "ai-sandbox" }],
  },
  {
    id: "vitest",
    label: "Vitest",
    group: "testing",
    rolePriority: "shared",
    evidenceRefs: [{ kind: "project", id: "ai-sandbox" }],
  },
] satisfies Skill[];
